//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingITGalishnikov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arenda
    {
        public int ID_rent { get; set; }
        public Nullable<int> ID_tenant { get; set; }
        public Nullable<int> Number_SC { get; set; }
        public Nullable<int> ID_employee { get; set; }
        public string Number_Pavilion { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Start_Rent { get; set; }
        public Nullable<System.DateTime> End_Rent { get; set; }
    
        public virtual Arendatory Arendatory { get; set; }
        public virtual Pavilioni Pavilioni { get; set; }
        public virtual Sotrudniki Sotrudniki { get; set; }
    }
}
